// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (ip_dst[16-1:0] ^ tcp_dport[16-1:0] == 0) && 
// (tcp_ack[32-1:0] == 1) && (ip_id[16-1:0] == 0) && 
// (tcp_window[16-1:0] == 17520) && (tcp_sport[16-1:0] == 80)

module gen_number_11 (
    input clk,
    input valid,
    input [15:0] ip_dst,
    input [15:0] tcp_dport,
    input [31:0] tcp_ack,
    input [15:0] ip_id,
    input [15:0] tcp_window,
    input [15:0] tcp_sport,
    output reg fp_detected
);

    reg [15:0] ip_dst_f;
    reg [15:0] tcp_dport_f;
    reg [31:0] tcp_ack_f;
    reg [15:0] ip_id_f;
    reg [15:0] tcp_window_f;
    reg [15:0] tcp_sport_f;
    reg valid_f;

    always @(posedge clk)
        ip_dst_f <= ip_dst;

    always @(posedge clk)
        tcp_dport_f <= tcp_dport;

    always @(posedge clk)
        tcp_ack_f <= tcp_ack;

    always @(posedge clk)
        ip_id_f <= ip_id;

    always @(posedge clk)
        tcp_window_f <= tcp_window;

    always @(posedge clk)
        tcp_sport_f <= tcp_sport;

    always @(posedge clk)
        valid_f <= valid;

    always @(posedge clk) begin
        if (valid_f)
            fp_detected <= 
                ((ip_dst_f ^ tcp_dport_f) == 16'd0) &&
                (tcp_ack_f == 32'd1) &&
                (ip_id_f == 16'd0) &&
                (tcp_window_f == 16'd17520) &&
                (tcp_sport_f == 16'd80);
        else
            fp_detected <= 1'b0;
    end

endmodule