// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (tcp_seq[32-1:0] == 3000) && (tcp_window[16-1:0] == 65535)

module gen_number_7 (
    input clk,
    input valid,
    input [31:0] tcp_seq,
    input [15:0] tcp_window,
    output reg fp_detected
);

    reg [31:0] tcp_seq_f;
    reg [15:0] tcp_window_f;
    reg valid_f;

    always @(posedge clk)
        tcp_seq_f <= tcp_seq;

    always @(posedge clk)
        tcp_window_f <= tcp_window;

    always @(posedge clk)
        valid_f <= valid;

    always @(posedge clk) begin
        if (valid_f)
            fp_detected <= (tcp_seq_f == 32'd3000) && (tcp_window_f == 16'd65535);
        else
            fp_detected <= 1'b0;
    end

endmodule