// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (ip_dst[31:0] ^ tcp_seq[31:0] == 0)

module gen_number_6( 

    input clk,
    input valid,
    input [31:0] ip_dst,
    input [31:0] tcp_seq,

    output reg fp_detected 

); 
	 
    reg [31:0] tcp_seq_f;
    reg valid_f;

    // Pipeline registers
    always @(posedge clk) begin
        tcp_seq_f <= tcp_seq;
        valid_f   <= valid;
    end

    // Detection logic
    always @(posedge clk) begin 
        if (valid_f)
            fp_detected <= (tcp_seq_f == 333994513);
        else
            fp_detected <= 1'b0; 
    end 

endmodule
