// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (ip_dst[16-1:0] ^ tcp_dport[16-1:0] ^ 
//  ip_id[16-1:0] ^ tcp_seq[16-1:0] == 0)

module gen_number_14 (
    input clk,
    input valid,
    input [15:0] ip_dst,
    input [15:0] tcp_dport,
    input [15:0] ip_id,
    input [15:0] tcp_seq,
    output reg fp_detected
);

    reg [15:0] ip_dst_f;
    reg [15:0] tcp_dport_f;
    reg [15:0] ip_id_f;
    reg [15:0] tcp_seq_f;
    reg valid_f;

    always @(posedge clk)
        ip_dst_f <= ip_dst;

    always @(posedge clk)
        tcp_dport_f <= tcp_dport;

    always @(posedge clk)
        ip_id_f <= ip_id;

    always @(posedge clk)
        tcp_seq_f <= tcp_seq;

    always @(posedge clk)
        valid_f <= valid;

    always @(posedge clk) begin
        if (valid_f)
            fp_detected <= 
                ((ip_dst_f ^ tcp_dport_f ^ ip_id_f ^ tcp_seq_f) == 16'd0);
        else
            fp_detected <= 1'b0;
    end

endmodule