// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (ip_dst[31:0] ^ tcp_seq[31:0] == 0)

module gen_number_1( 

    input clk,
    input valid,
    input [15:0] tcp_window,

    output reg fp_detected 

); 

    reg [15:0] tcp_window_f;
    reg valid_f;

    // Pipeline registers
    always @(posedge clk) begin
        tcp_window_f <= tcp_window;
        valid_f   <= valid;
    end

    // Detection logic
    always @(posedge clk) begin 
        if (valid_f)
            fp_detected <= (tcp_window_f == 14600);
        else
            fp_detected <= 1'b0; 
    end 

endmodule
