// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (ip_dst[31:0] ^ tcp_seq[31:0] == 0)

module gen_number_4( 

    input clk,
    input valid,
    input [31:0] ip_dst,
    input [31:0] tcp_seq,
	 input [15:0] tcp_window,

    output reg fp_detected 

); 

    reg [31:0] ip_dst_f;
    reg [31:0] tcp_seq_f;
    reg [15:0] tcp_window_f;
    reg valid_f;

    // Pipeline registers
    always @(posedge clk) begin
        ip_dst_f <= ip_dst;
        tcp_seq_f <= tcp_seq;
        valid_f   <= valid;
		  tcp_window_f <= tcp_window;
    end

    // Detection logic
    always @(posedge clk) begin 
        if (valid_f)
            fp_detected <= ((ip_dst_f ^ tcp_seq_f) == 3232235778) && ((tcp_window_f) == 1300);
        else
            fp_detected <= 1'b0; 
    end 

endmodule
