// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (ip_id[16-1:0] == 54321)

module gen_number_15 (
    input clk,
    input valid,
    input [15:0] ip_id,
    output reg fp_detected
);

    reg [15:0] ip_id_f;
    reg valid_f;

    always @(posedge clk)
        ip_id_f <= ip_id;

    always @(posedge clk)
        valid_f <= valid;

    always @(posedge clk) begin
        if (valid_f)
            fp_detected <= (ip_id_f == 16'd54321);
        else
            fp_detected <= 1'b0;
    end

endmodule