// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (tcp_seq[32-1:0] == 100) && (ip_id[16-1:0] == 123) && (tcp_window[16-1:0] == 1024)

module gen_number_17 (
    input clk,
    input valid,
    input [31:0] tcp_seq,
    input [15:0] ip_id,
    input [15:0] tcp_window,
    output reg fp_detected
);

    reg [31:0] tcp_seq_f;
    reg [15:0] ip_id_f;
    reg [15:0] tcp_window_f;
    reg valid_f;

    always @(posedge clk)
        tcp_seq_f <= tcp_seq;

    always @(posedge clk)
        ip_id_f <= ip_id;

    always @(posedge clk)
        tcp_window_f <= tcp_window;

    always @(posedge clk)
        valid_f <= valid;

    always @(posedge clk) begin
        if (valid_f)
            fp_detected <= 
                (tcp_seq_f == 32'd100) &&
                (ip_id_f == 16'd123) &&
                (tcp_window_f == 16'd1024);
        else
            fp_detected <= 1'b0;
    end

endmodule