// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (tcp_window[16-1:0] == 0)

module gen_number_16 (
    input clk,
    input valid,
    input [15:0] tcp_window,
    output reg fp_detected
);

    reg [15:0] tcp_window_f;
    reg valid_f;

    always @(posedge clk)
        tcp_window_f <= tcp_window;

    always @(posedge clk)
        valid_f <= valid;

    always @(posedge clk) begin
        if (valid_f)
            fp_detected <= (tcp_window_f == 16'd0);
        else
            fp_detected <= 1'b0;
    end

endmodule