// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
// (tcp_dport[16-1:0] == 5431) && (tcp_sport[16-1:0] == 6) && 
// (tcp_window[16-1:0] == 65535) && (tcp_seq[32-1:0] == 0) && 
// (tcp_ack[32-1:0] == 0) && (ip_id[16-1:0] == 54321)

module gen_number_8 (
    input clk,
    input valid,
    input [15:0] tcp_dport,
    input [15:0] tcp_sport,
    input [15:0] tcp_window,
    input [31:0] tcp_seq,
    input [31:0] tcp_ack,
    input [15:0] ip_id,
    output reg fp_detected
);

    reg [15:0] tcp_dport_f;
    reg [15:0] tcp_sport_f;
    reg [15:0] tcp_window_f;
    reg [31:0] tcp_seq_f;
    reg [31:0] tcp_ack_f;
    reg [15:0] ip_id_f;
    reg valid_f;

    always @(posedge clk)
        tcp_dport_f <= tcp_dport;

    always @(posedge clk)
        tcp_sport_f <= tcp_sport;

    always @(posedge clk)
        tcp_window_f <= tcp_window;

    always @(posedge clk)
        tcp_seq_f <= tcp_seq;

    always @(posedge clk)
        tcp_ack_f <= tcp_ack;

    always @(posedge clk)
        ip_id_f <= ip_id;

    always @(posedge clk)
        valid_f <= valid;

    always @(posedge clk) begin
        if (valid_f)
            fp_detected <= 
                (tcp_dport_f == 16'd5431) &&
                (tcp_sport_f == 16'd6) &&
                (tcp_window_f == 16'd65535) &&
                (tcp_seq_f == 32'd0) &&
                (tcp_ack_f == 32'd0) &&
                (ip_id_f == 16'd54321);
        else
            fp_detected <= 1'b0;
    end

endmodule