// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
 // (tcp_seq[32-1:0] == 333994513) 

 module gen_number_6( 

	input	bit	clk,
	input	bit	valid,
	input 	 bit 	 [32-1:0] 	 tcp_seq,

	output 	 logic 	 fp_detected 

 ); 

	bit [32-1:0] 	 tcp_seq_f;
	bit valid_f;
	always @ (posedge clk) 
		tcp_seq_f <= tcp_seq;

	always @ (posedge clk) 
		valid_f <= valid;

	always @ (posedge clk) begin 
		if(valid_f)
			fp_detected <= (tcp_seq_f[32-1:0] == 333994513);
		 else
			fp_detected <= 0; 
	end 

 endmodule 
