// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
 // (ip_dst[32-1:0] ^ tcp_seq[32-1:0] == 0) 

 module gen_number_0( 

	input	bit	clk,
	input	bit	valid,
	input 	 bit 	 [32-1:0] 	 ip_dst,
	input 	 bit 	 [32-1:0] 	 tcp_seq,

	output 	 logic 	 fp_detected 

 ); 

	bit [32-1:0] 	 ip_dst_f;
	bit [32-1:0] 	 tcp_seq_f;
	bit valid_f;
	always @ (posedge clk) 
		ip_dst_f <= ip_dst;

	always @ (posedge clk) 
		tcp_seq_f <= tcp_seq;

	always @ (posedge clk) 
		valid_f <= valid;

	always @ (posedge clk) begin 
		if(valid_f)
			fp_detected <= (ip_dst_f[32-1:0] ^ tcp_seq_f[32-1:0] == 0);
		 else
			fp_detected <= 0; 
	end 

 endmodule 
