// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
 // (ip_dst[16-1:0] ^ tcp_dport[16-1:0] == 0) && (tcp_ack[32-1:0] == 1) && (ip_id[16-1:0] == 38993) 

 module gen_number_12( 

	input	bit	clk,
	input	bit	valid,
	input 	 bit 	 [16-1:0] 	 ip_dst,
	input 	 bit 	 [16-1:0] 	 tcp_dport,
	input 	 bit 	 [32-1:0] 	 tcp_ack,
	input 	 bit 	 [16-1:0] 	 ip_id,

	output 	 logic 	 fp_detected 

 ); 

	bit [16-1:0] 	 ip_dst_f;
	bit [16-1:0] 	 tcp_dport_f;
	bit [32-1:0] 	 tcp_ack_f;
	bit [16-1:0] 	 ip_id_f;
	bit valid_f;
	always @ (posedge clk) 
		ip_dst_f <= ip_dst;

	always @ (posedge clk) 
		tcp_dport_f <= tcp_dport;

	always @ (posedge clk) 
		tcp_ack_f <= tcp_ack;

	always @ (posedge clk) 
		ip_id_f <= ip_id;

	always @ (posedge clk) 
		valid_f <= valid;

	always @ (posedge clk) begin 
		if(valid_f)
			fp_detected <= (ip_dst_f[16-1:0] ^ tcp_dport_f[16-1:0] == 0) && (tcp_ack_f[32-1:0] == 1) && (ip_id_f[16-1:0] == 38993);
		 else
			fp_detected <= 0; 
	end 

 endmodule 
