// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
 // (ip_id[16-1:0] == 54321) 

 module gen_number_15( 

	input	bit	clk,
	input	bit	valid,
	input 	 bit 	 [16-1:0] 	 ip_id,

	output 	 logic 	 fp_detected 

 ); 

	bit [16-1:0] 	 ip_id_f;
	bit valid_f;
	always @ (posedge clk) 
		ip_id_f <= ip_id;

	always @ (posedge clk) 
		valid_f <= valid;

	always @ (posedge clk) begin 
		if(valid_f)
			fp_detected <= (ip_id_f[16-1:0] == 54321);
		 else
			fp_detected <= 0; 
	end 

 endmodule 
