// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
 // (tcp_seq[32-1:0] == 100) && (ip_id[16-1:0] == 123) && (tcp_window[16-1:0] == 1024) 

 module gen_number_17( 

	input	bit	clk,
	input	bit	valid,
	input 	 bit 	 [32-1:0] 	 tcp_seq,
	input 	 bit 	 [16-1:0] 	 ip_id,
	input 	 bit 	 [16-1:0] 	 tcp_window,

	output 	 logic 	 fp_detected 

 ); 

	bit [32-1:0] 	 tcp_seq_f;
	bit [16-1:0] 	 ip_id_f;
	bit [16-1:0] 	 tcp_window_f;
	bit valid_f;
	always @ (posedge clk) 
		tcp_seq_f <= tcp_seq;

	always @ (posedge clk) 
		ip_id_f <= ip_id;

	always @ (posedge clk) 
		tcp_window_f <= tcp_window;

	always @ (posedge clk) 
		valid_f <= valid;

	always @ (posedge clk) begin 
		if(valid_f)
			fp_detected <= (tcp_seq_f[32-1:0] == 100) && (ip_id_f[16-1:0] == 123) && (tcp_window_f[16-1:0] == 1024);
		 else
			fp_detected <= 0; 
	end 

 endmodule 
