// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
 // (ip_id[16-1:0] == 256) && (tcp_window[16-1:0] == 16384) && (tcp_seq[16-1:0] == 0) && (tcp_ack[32-1:0] == 0) && (tcp_sport[16-1:0] == 6000) 

 module gen_number_9( 

	input	bit	clk,
	input	bit	valid,
	input 	 bit 	 [16-1:0] 	 ip_id,
	input 	 bit 	 [16-1:0] 	 tcp_window,
	input 	 bit 	 [16-1:0] 	 tcp_seq,
	input 	 bit 	 [32-1:0] 	 tcp_ack,
	input 	 bit 	 [16-1:0] 	 tcp_sport,

	output 	 logic 	 fp_detected 

 ); 

	bit [16-1:0] 	 ip_id_f;
	bit [16-1:0] 	 tcp_window_f;
	bit [16-1:0] 	 tcp_seq_f;
	bit [32-1:0] 	 tcp_ack_f;
	bit [16-1:0] 	 tcp_sport_f;
	bit valid_f;
	always @ (posedge clk) 
		ip_id_f <= ip_id;

	always @ (posedge clk) 
		tcp_window_f <= tcp_window;

	always @ (posedge clk) 
		tcp_seq_f <= tcp_seq;

	always @ (posedge clk) 
		tcp_ack_f <= tcp_ack;

	always @ (posedge clk) 
		tcp_sport_f <= tcp_sport;

	always @ (posedge clk) 
		valid_f <= valid;

	always @ (posedge clk) begin 
		if(valid_f)
			fp_detected <= (ip_id_f[16-1:0] == 256) && (tcp_window_f[16-1:0] == 16384) && (tcp_seq_f[16-1:0] == 0) && (tcp_ack_f[32-1:0] == 0) && (tcp_sport_f[16-1:0] == 6000);
		 else
			fp_detected <= 0; 
	end 

 endmodule 
