// Generated by DELL on 2025-05-26 at 10:56:28
// Auto-Generated sub-module for 
 // (tcp_window[16-1:0] == 1300) && (tcp_ack[32-1:0] == 0) 

 module gen_number_13( 

	input	bit	clk,
	input	bit	valid,
	input 	 bit 	 [16-1:0] 	 tcp_window,
	input 	 bit 	 [32-1:0] 	 tcp_ack,

	output 	 logic 	 fp_detected 

 ); 

	bit [16-1:0] 	 tcp_window_f;
	bit [32-1:0] 	 tcp_ack_f;
	bit valid_f;
	always @ (posedge clk) 
		tcp_window_f <= tcp_window;

	always @ (posedge clk) 
		tcp_ack_f <= tcp_ack;

	always @ (posedge clk) 
		valid_f <= valid;

	always @ (posedge clk) begin 
		if(valid_f)
			fp_detected <= (tcp_window_f[16-1:0] == 1300) && (tcp_ack_f[32-1:0] == 0);
		 else
			fp_detected <= 0; 
	end 

 endmodule 
